class AppendMetadataMiddleware:
    """
    Middleware class that appends the 'metadata' include parameter to requests for specific API paths.

    This middleware checks if the request path starts with one of the specified prefixes, and if so,
    appends the 'metadata' include parameter to the request GET parameters.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        """
        Process the request and add the 'metadata' include parameter if the request path starts with a specified prefix.

        :param request: The incoming request object.
        :return: The response generated by the get_response function.
        """
        path_prefixes = [
            "/api/v2/resources/",
            "/api/v2/datasets/",
            "/api/v2/maps/",
            "/api/v2/documents/",
            "/api/v2/geoapps/",
        ]

        if any(request.path.startswith(prefix) for prefix in path_prefixes):
            includes = request.GET.get("include[]")
            request.GET = request.GET.copy()
            request.GET["include[]"] = "metadata"
            if includes:
                request.GET.appendlist("include[]", includes)

        return self.get_response(request)
